apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: eu.gcr.io/raffertymenu/backend
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
          - name: DB_USERNAME
            value: menuser
          - name: DB_PASSWORD
            value: yourStrong@Password 
          - name: DB_HOSTNAME
            value: menupostgres-postgresql
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 80
