apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: eu.gcr.io/raffertymenu/backend
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: menu-postgresql
                key: postgresql-password
          - name: DB_HOSTNAME
            value: menu-postgresql
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 3000
